/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.*;
import static org.junit.Assert.*;

public class AppTest {
    // @Test
    // public void testUnitTesting(){
    //     assertEquals(1, 1);
    // }

    // @Test
    // public void testPlayer1(){
    //     Player p1 = new Player("Zhongli", 5);
    //     p1.updateRoll();
    //     assertEquals(6, p1.getRollCount());
    // }

    // @Before
    // public void setUp(){
    //     System.out.println("before junit");
    // }

    // @After
    // public void tearDown(){
    //     System.out.println("after junit");
    // }

    // @BeforeClass
    // public static void init(){
    //     System.out.println("start testing");
    // }

    // @AfterClass
    // public static void done(){
    //     System.out.println("done testing");
    // }
}
