/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.*;
import static org.junit.Assert.*;

public class AppTest2{
    private Player p;
    public AppTest2(){
        this.p = new Player("Zhongli", 5);
    }

    @Test
    public void testPlayer1(){
        String result = this.p.rollGacha(3);
        assertEquals("R", result);
        assertEquals(6,this.p.getRollCount());
    }

    @Test
    public void testPlayer2(){
        String result = this.p.rollGacha(4);
        assertEquals("SR", result);
        assertEquals(6,this.p.getRollCount());
    }

    @Test
    public void testPlayer3(){
        String result = this.p.rollGacha(5);
        assertEquals("SSR", result);
        assertEquals(6,this.p.getRollCount());
    }
}
