/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.*;
import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class AppTest4{
    private Player p;
    private Machine gacha;

    public AppTest4(){
        this.p = new Player("Zhongli", 5);
        this.gacha = mock(Machine.class);
    }

    @Test
    public void testPlayer1(){
        when(this.gacha.roll()).thenReturn(3);
        String result = this.p.rollGacha(this.gacha);
        assertEquals("R", result);
    }
    
    @Test
    public void testPlayer2(){
        when(this.gacha.roll()).thenReturn(4);
        String result = this.p.rollGacha(this.gacha);
        assertEquals("SR", result);
    }
    @Test
    public void testPlayer3(){
        when(this.gacha.roll()).thenReturn(5);
        String result = this.p.rollGacha(this.gacha);
        assertEquals("SSR", result);
    }

}
